apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-config
  namespace: oficina
data:
  DB_URL: "jdbc:postgresql://postgres:5432/oficina"
  JWT_EXPIRATION: "86400000"
  MAIL_HOST: "mailpit"
  MAIL_PORT: "1025"
  MAIL_AUTH: "false"
  MAIL_STARTTLS: "false"
  MAIL_FROM: "oficina@localhost"
  SERVER_PORT: "8080"
