apiVersion: v1
kind: Secret
metadata:
  name: oficina-secret
  namespace: oficina
type: Opaque
stringData:
  DB_USERNAME: "oficina"
  DB_PASSWORD: "oficina123"
  # Em produção: substitua por uma chave base64 segura gerada com:
  # openssl rand -base64 64
  JWT_SECRET: "bXlTdXBlclNlY3JldEtleUZvckpXVFN5c3RlbU9maWNpbmFNZWNhbmljYTIwMjQ="
  # Credenciais de e-mail (Gmail em produção)
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
