apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: oficina
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"ghcr.io":{"username":"placeholder","password":"placeholder-local","auth":"cGxhY2Vob2xkZXI6cGxhY2Vob2xkZXItbG9jYWw="}}}'
