apiVersion: v1
kind: Service
metadata:
  name: mailpit
  namespace: oficina
spec:
  selector:
    app: mailpit
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
    - name: ui
      port: 8025
      targetPort: 8025
      # NodePort para acessar a UI do Mailpit via localhost:30825 no kind
      # Em cloud: remova nodePort e altere type para ClusterIP
      nodePort: 30825
  type: NodePort
