apiVersion: v1
kind: Service
metadata:
  name: oficina-app
  namespace: oficina
spec:
  selector:
    app: oficina-app
  ports:
    - port: 8080
      targetPort: 8080
      # NodePort para acessar via localhost:30080 no kind
      # Em cloud: remova nodePort e altere type para LoadBalancer
      nodePort: 30080
  type: NodePort
